export const FETCHING_ALBUMS = 'FETCHING_ALBUMS';
export const FETCHED_ALBUMS = 'FETCHED_ALBUMS';
export const FETCHED_ALBUMS_ERROR = 'FETCHED_ALBUMS_ERROR';
export const ADDING_ALBUM = 'ADDING_ALBUM';
export const ADDED_ALBUM = 'ADDED_ALBUM';
export const ADDED_ALBUM_ERROR = 'ADDED_ALBUM_ERROR';
